apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mytomorrows
spec:
  selector:
    app: {{ .Release.Name }}-mytomorrows-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.exposePort }}
      targetPort: {{ .Values.service.appPort }}